activate: false
default_reply: "[]"
model: deepseek-v3 # gpt-4o-mini-ca
version: prompt_v1
system_prompt:
  prompt_v1: |
    你是一个用于实体关系分析与抽取的工具。我将提供给你一些聊天数据，你需要按要求抽取实体关系，并以markdown的格式输出结果。
prompts: 
  prompt_v1: |
    ## 任务描述：
    我拥有一组群聊信息，每条消息将遵从以下格式：
    ```
    [用户名][时间]: '发送的消息'
    ```
    请你依据群聊信息，帮我总结详细的、有意义的实体关系元组

    ## 具体的群聊消息如下：
    ${text}

    ## 任务要求与输出格式：
    - 一条实体关系元组是一个包含sbj、sbj_label、obj、obj_label、rela、desc六个key的字典，其value分别表示主体、主体的类型标签、客体、客体的类型标签、关系、对关系的描述
    - 主体和客体的类型只能从以下标签选择：人物、组织、地点、事件、时间、产品、公司、职位、作品、疾病、药物、技术、学科、品牌、法律、语言、设备、项目、机构、其他
    - 你最终需要总结生成一组实体关系三元组**列表**，格式如下：
    ```json
    [
      {
        "sbj": "此处填充关系主体",
        "sbj_label": "此处填充关系主体的类型标签",
        "obj": "此处填充关系客体",
        "obj_label": "此处填充关系客体的类型标签",
        "rela": "此处填充关系",
        "desc": "此处填充你对这个关系的描述(一小句话)"
      },
    ]
    ```
    - 抽取出的实体关系元组数量基于实际情况而定
    - 请你充分识别用户名、时间等信息，先一步步思考并分析聊天的内容，最后再总结全部的实体关系三元组

    现在请开始
